# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBS_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
