# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0002_bbs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='create_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bbs',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
