# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0004_auto_20170115_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BBS.Category'),
            preserve_default=False,
        ),
    ]
