# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BBS', '0005_bbs_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bbs',
            name='cate',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='BBS.Category'),
        ),
        migrations.AlterField(
            model_name='bbs_user',
            name='signature',
            field=models.CharField(blank=True, default='this guy is to lazy to leave any thing here.', max_length=128, null=True),
        ),
    ]
