# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0009_auto_20170123_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs_title',
            options={'permissions': (('view_bbs_title', 'can view bbs_title'),)},
        ),
    ]
